export { ApiError, API_BASE_URL, NEL_V2_API_BASE_URL, request } from "./fetcher";
export type { RequestContext, RequestOptions } from "./fetcher";

export { getHealth } from "./v1";
export type { HealthResponse } from "./v1";

export {
  getV2UserConfig,
  saveV2UserConfig,
  listNelModels,
  listTaxonomyModels,
  listApiKeys,
  createApiKey,
  deleteApiKey,
  classify,
  LINKABLE_ENTITY_TYPES,
  listPlugins,
  getPlugin,
  getPluginOptions,
  listPipelines,
  getPipeline,
  createPipeline,
  updatePipeline,
  deletePipeline,
  activatePipeline,
  clonePipeline,
  validatePipeline,
} from "./v2";
export type {
  NelModel,
  TaxonomyModel,
  V2UserConfig,
  ApiKeyMetadata,
  ListApiKeysResponse,
  CreateApiKeyResponse,
  ClassifyEntityType,
  ClassifyEntitySpan,
  ClassifyOccupationEntity,
  ClassifySkillEntity,
  ClassifyQualificationEntity,
  ClassifyMatchEntity,
  ClassifyOccupationMatch,
  ClassifySkillMatch,
  ClassifyQualificationMatch,
  ClassifyMatch,
  ClassifiedEntity,
  ClassifyOptions,
  ClassifyRequest,
  ClassifyMetadata,
  ClassifyResponse,
  ClassifyPipelineSummary,
  PipelineStageSummary,
  PluginStatus,
  PluginCategory,
  PluginCapabilities,
  PluginSummary,
  ListPluginsResponse,
  PluginSlot,
  PluginManifest,
  PluginDetail,
  PluginOptionItem,
  PluginOptionsResponse,
  Pipeline,
  PipelineStage,
  ListPipelinesResponse,
  CreatePipelineRequest,
  UpdatePipelineRequest,
  PipelineValidationIssue,
  ValidatePipelineRequest,
  ValidatePipelineResponse,
} from "./v2";
