/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Source: backend/tabiya_plugin_contracts/contracts/*.schema.json
 * Generator: backend/tabiya_plugin_contracts/scripts/export_ts_types.py
 *
 * To regenerate:
 *   cd backend/tabiya_plugin_contracts
 *   python scripts/export_json_schema.py
 *   python scripts/export_ts_types.py
 *
 * CI re-runs both scripts and fails on a non-empty git diff.
 *
 * Each schema is emitted into its own namespace so field-level types
 * (e.g. `Detail`, `Message`) don't collide. Consumers typically import
 * the root types re-exported at the bottom of this file.
 */

/* eslint-disable */

// ─── from manifest.schema.json ─────────────────────────────────────────
export namespace ManifestNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "PluginCategory".
 */
export type PluginCategory = "source" | "core" | "transform" | "sink";
export type Detail = string | null;
/**
 * Key into the frontend's icon map.
 */
export type Icon = string;
export type Cardinality = "single" | "none";
/**
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "SlotType".
 */
export type SlotType = "None" | "RawText" | "RawTextStream" | "Entities" | "LinkedEntities";
export type Name = string;
/**
 * Dotted, version-suffixed identifier. Example: tabiya.ner.v1
 */
export type PluginId = string;
export type Summary = string;
/**
 * Per-invoke deadline enforced by the orchestrator.
 */
export type TimeoutMs = number;
/**
 * Semver of the plugin implementation itself.
 */
export type Version = string;
export type XTabiyaBatchMax = number | null;
export type XTabiyaCancellable = boolean | null;
/**
 * Contract version the plugin was built against. Auto-emitted by the adapter helper.
 */
export type XTabiyaContractVersion = string | null;
export type XTabiyaIdempotent = boolean | null;
export type XTabiyaStreams = boolean | null;

/**
 * Static metadata returned by `GET /plugin/manifest`.
 *
 * The `x-tabiya-*` extension fields are declared as explicit optionals to
 * keep the JSON Schema readable; unknown extension fields are also allowed
 * so plugin authors can add their own without touching this package.
 */
export interface Manifest {
  category: PluginCategory;
  config_schema?: ConfigSchema;
  detail?: Detail;
  icon: Icon;
  input_slot: Slot;
  name: Name;
  output_slot: Slot;
  plugin_id: PluginId;
  summary: Summary;
  timeout_ms?: TimeoutMs;
  version: Version;
  "x-tabiya-batch-max"?: XTabiyaBatchMax;
  "x-tabiya-cancellable"?: XTabiyaCancellable;
  "x-tabiya-contract-version"?: XTabiyaContractVersion;
  "x-tabiya-idempotent"?: XTabiyaIdempotent;
  "x-tabiya-streams"?: XTabiyaStreams;
  [k: string]: unknown;
}
/**
 * Hand-rolled JSON Schema subset used by the editor's ConfigForm and by invoke-time config validation. May include the `x-source` extension field pointing at a plugin options endpoint for dynamic dropdowns.
 */
export interface ConfigSchema {
  [k: string]: unknown;
}
/**
 * Manifest input_slot / output_slot descriptor.
 *
 * This interface was referenced by `Manifest`'s JSON-Schema
 * via the `definition` "Slot".
 */
export interface Slot {
  cardinality?: Cardinality;
  type: SlotType;
}

}

// ─── from invoke_request.schema.json ─────────────────────────────────────────
export namespace InvokeRequestNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Wall-clock deadline the plugin SHOULD respect. Adapter enforces a hard timeout on top.
 */
export type DeadlineMs = number;
export type PipelineId = string | null;
export type RequestId = string;
export type StageIndex = number;
export type UserId = string | null;

export interface InvokeRequest {
  config?: Config;
  context: Context;
  input?: Input;
}
export interface Config {
  [k: string]: unknown;
}
/**
 * Per-invoke context passed to Core functions.
 *
 * Adapters populate this from the HTTP request (or from a test fixture in
 * the in-process adapter).
 *
 * This interface was referenced by `InvokeRequest`'s JSON-Schema
 * via the `definition` "Context".
 */
export interface Context {
  deadline_ms?: DeadlineMs;
  pipeline_id?: PipelineId;
  request_id: RequestId;
  stage_index?: StageIndex;
  user_id?: UserId;
}
/**
 * Slot payload matching manifest.input_slot.type. Adapter parses this against SLOT_MODEL_BY_TYPE.
 */
export interface Input {
  [k: string]: unknown;
}

}

// ─── from invoke_response.schema.json ─────────────────────────────────────────
export namespace InvokeResponseNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Free-form per-stage metadata (model_name, processing_time_ms, …).
 */
export type Metadata = {
  [k: string]: unknown;
} | null;

export interface InvokeResponse {
  metadata?: Metadata;
  output?: Output;
}
/**
 * Slot payload matching manifest.output_slot.type.
 */
export interface Output {
  [k: string]: unknown;
}

}

// ─── from error_envelope.schema.json ─────────────────────────────────────────
export namespace ErrorEnvelopeNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `ErrorEnvelope`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode =
  "PLUGIN_INTERNAL" | "BAD_INPUT" | "TIMEOUT" | "UPSTREAM_UNAVAILABLE" | "CONFIG_INVALID" | "UNAVAILABLE";
export type Detail = {
  [k: string]: unknown;
} | null;
export type Message = string;

export interface ErrorEnvelope {
  code: ErrorCode;
  detail?: Detail;
  message: Message;
}

}

// ─── from health.schema.json ─────────────────────────────────────────
export namespace HealthNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Detail = string | null;
/**
 * This interface was referenced by `Health`'s JSON-Schema
 * via the `definition` "HealthStatus".
 */
export type HealthStatus = "ok" | "degraded" | "down";

export interface Health {
  detail?: Detail;
  status: HealthStatus;
}

}

// ─── from slots.schema.json ─────────────────────────────────────────
export namespace SlotsNs {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EntityType = string;
export type End = number;
export type Start = number;
export type SurfaceForm = string;
export type Entities1 = Entity[];
export type SourceText = string;
export type EntityType1 = string;
export type Id = string;
export type PreferredLabel = string;
export type Score = number;
export type Uri = string | null;
export type Matches = Match[];
export type SurfaceForm1 = string;
export type Entities2 = LinkedEntity[];
export type SourceText1 = string;
export type Kind = "None";
export type Text = string;
export type JobId = string;
export type Text1 = string;
export type Items = RawTextStreamItem[];

export interface SlotPayloads {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "Entities".
 */
export interface Entities {
  entities: Entities1;
  source_text: SourceText;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "Entity".
 */
export interface Entity {
  entity_type: EntityType;
  span: EntitySpan;
  surface_form: SurfaceForm;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "EntitySpan".
 */
export interface EntitySpan {
  end: End;
  start: Start;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "LinkedEntities".
 */
export interface LinkedEntities {
  entities: Entities2;
  source_text: SourceText1;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "LinkedEntity".
 */
export interface LinkedEntity {
  entity_type: EntityType1;
  matches?: Matches;
  span: EntitySpan;
  surface_form: SurfaceForm1;
}
/**
 * A single ESCO/taxonomy match for a linked entity.
 *
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "Match".
 */
export interface Match {
  id: Id;
  preferred_label: PreferredLabel;
  score: Score;
  uri?: Uri;
}
/**
 * Sentinel payload for Source inputs and Sink outputs.
 *
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "NoneSlot".
 */
export interface NoneSlot {
  kind?: Kind;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "RawText".
 */
export interface RawText {
  text: Text;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "RawTextStream".
 */
export interface RawTextStream {
  items: Items;
}
/**
 * This interface was referenced by `SlotPayloads`'s JSON-Schema
 * via the `definition` "RawTextStreamItem".
 */
export interface RawTextStreamItem {
  job_id: JobId;
  text: Text1;
}

}

// ─── Root type re-exports ─────────────────────────────────────────────
// Import these directly; the namespaces above are an implementation detail
// of the codegen and may be reorganised without a breaking change.

export type Manifest = ManifestNs.Manifest;
export type InvokeRequest = InvokeRequestNs.InvokeRequest;
export type InvokeResponse = InvokeResponseNs.InvokeResponse;
export type ErrorEnvelope = ErrorEnvelopeNs.ErrorEnvelope;
export type Health = HealthNs.Health;
export type SlotPayloads = SlotsNs.SlotPayloads;
