"""Firebase Identity Platform configuration.

Enables Identity Platform on the GCP project and configures:
  - Email/password sign-in
  - Authorized domains (frontend domain + localhost for dev)
"""

import pulumi
import pulumi_gcp as gcp


def configure_identity_platform(project: str, authorized_domains: list[str]) -> pulumi.Output:
    cfg = gcp.identityplatform.Config(
        "identity-platform-config",
        project=project,
        autodelete_anonymous_users=False,
        sign_in=gcp.identityplatform.ConfigSignInArgs(
            allow_duplicate_emails=False,
            email=gcp.identityplatform.ConfigSignInEmailArgs(
                enabled=True,
                password_required=True,
            ),
        ),
        authorized_domains=authorized_domains,
    )

    # The Web API key is auto-generated by GCP when Identity Platform is enabled.
    # It lives on the client sub-object and is needed by the frontend to initialise Firebase.
    api_key = cfg.client.apply(lambda c: c.get("api_key") if c else "")
    return api_key
