#!/usr/bin/env python3
"""Seed the nel_qualifications collection from the qualifications CSV.

DESCRIPTION
-----------
Reads the qualifications CSV bundled with the legacy NEL service and upserts
each row into the `nel_qualifications` MongoDB collection.  Qualification
embeddings are later generated by generate_embeddings.py.

This script is idempotent — re-running it is safe and will update any rows
whose data has changed without creating duplicates.

By default the script runs in DRY-RUN mode: it reads the CSV and logs what
*would* be upserted, but writes nothing to the database.
Pass --hot-run to perform actual writes.

REQUIRED ENV VARS
-----------------
  APPLICATION_MONGODB_URI     App DB connection string (nel_qualifications lives here)

OPTIONAL ENV VARS
-----------------
  APPLICATION_DATABASE_NAME   Default: tabiya-classifier

CSV SOURCE
----------
  backend/nel/nel/files/qualifications.csv
  (relative to the repository root — auto-discovered)

EXAMPLES
--------
  # Dry-run (safe, no writes):
  python scripts/seed_qualifications.py

  # Hot-run — actually write to MongoDB:
  python scripts/seed_qualifications.py --hot-run

  # Point at a different CSV:
  python scripts/seed_qualifications.py --csv /path/to/qualifications.csv --hot-run
"""

import argparse
import asyncio
import logging
import logging.config
import os
import sys
import time
import uuid
from pathlib import Path

import yaml
from tqdm import tqdm

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent.parent  # scripts → nel_v2 → backend → repo root
sys.path.insert(0, str(_HERE.parent))   # nel_v2/ → `nel` package importable
sys.path.insert(0, str(_HERE))          # scripts/ → `_logging_handler` importable

from dotenv import load_dotenv
load_dotenv(_REPO_ROOT / ".env")

# ── Logging setup ─────────────────────────────────────────────────────────────
_cfg_path = _HERE / "logging.cfg.yaml"
with open(_cfg_path) as _f:
    logging.config.dictConfig(yaml.safe_load(_f))

logger = logging.getLogger(__name__)

# ── Imports ───────────────────────────────────────────────────────────────────
import pandas as pd
from motor.motor_asyncio import AsyncIOMotorClient

_DEFAULT_CSV = _REPO_ROOT / "backend" / "nel" / "nel" / "files" / "qualifications.csv"


# ── Main ──────────────────────────────────────────────────────────────────────

async def main(args: argparse.Namespace) -> None:
    hot_run: bool = args.hot_run
    csv_path = Path(args.csv)

    uri = os.environ["APPLICATION_MONGODB_URI"]
    db_name = os.environ.get("APPLICATION_DATABASE_NAME", "tabiya-classifier")

    mode_label = "HOT-RUN (writes enabled)" if hot_run else "DRY-RUN (no writes)"
    logger.info("=" * 60)
    logger.info("NEL Qualifications Seed — %s", mode_label)
    logger.info("  app DB   : %s", db_name)
    logger.info("  CSV      : %s", csv_path)
    logger.info("=" * 60)

    # ── [1/3] Read CSV ────────────────────────────────────────────────────────
    logger.info("[1/3] Reading qualifications CSV …")
    if not csv_path.exists():
        logger.error("CSV not found: %s", csv_path)
        sys.exit(1)

    df = pd.read_csv(csv_path)
    df.columns = [c.strip() for c in df.columns]
    records = df.to_dict(orient="records")

    valid_records = [
        r for r in records if str(r.get("qualification", "")).strip()
    ]
    skipped = len(records) - len(valid_records)
    logger.info(
        "  Found %d rows (%d valid, %d skipped — empty qualification name)",
        len(records), len(valid_records), skipped,
    )

    # ── [2/3] Connect ─────────────────────────────────────────────────────────
    logger.info("[2/3] Connecting to MongoDB (%s) …", db_name)
    client = AsyncIOMotorClient(uri, tlsAllowInvalidCertificates=True)
    db = client.get_database(db_name)
    col = db["nel_qualifications"]

    # ── [3/3] Upsert ──────────────────────────────────────────────────────────
    logger.info("[3/3] Upserting %d qualifications …", len(valid_records))
    t0 = time.monotonic()

    inserted = updated = unchanged = 0
    progress = tqdm(
        total=len(valid_records),
        desc="seeding qualifications",
        unit="row",
    )

    for row in valid_records:
        qualification = str(row.get("qualification", "")).strip()
        country = str(row.get("country", "")).strip()
        eqf_level = row.get("eqf_level")

        # Stable UUID derived from (qualification, country) — qualifications
        # have no UUID from the taxonomy API, so we generate one deterministically.
        stable_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"{qualification}|{country}"))
        doc = {
            "qualification": qualification,
            "country": country,
            "eqf_level": str(eqf_level) if eqf_level is not None else None,
            "UUID": stable_uuid,
            "originUUID": stable_uuid,
            "UUIDHistory": [stable_uuid],
            "originUri": "",
            "altLabels": [],
            "description": "",
        }

        if hot_run:
            result = await col.update_one(
                {"qualification": {"$eq": qualification}, "country": {"$eq": country}},
                {"$set": doc},
                upsert=True,
            )
            if result.upserted_id:
                inserted += 1
            elif result.modified_count:
                updated += 1
            else:
                unchanged += 1
        else:
            logger.debug(
                "[DRY-RUN] Would upsert: qualification=%r country=%r eqf_level=%r",
                qualification, country, eqf_level,
            )
            unchanged += 1  # treat all as "would-be unchanged" in dry-run

        progress.update(1)

    progress.close()
    elapsed = time.monotonic() - t0

    logger.info("=" * 60)
    if hot_run:
        logger.info(
            "Done in %.1fs — inserted: %d, updated: %d, unchanged: %d",
            elapsed, inserted, updated, unchanged,
        )
    else:
        logger.info(
            "Dry-run complete in %.1fs — would upsert %d rows (no writes made)",
            elapsed, len(valid_records),
        )
        logger.info("Re-run with --hot-run to perform actual writes.")
    logger.info("=" * 60)

    client.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--csv",
        default=str(_DEFAULT_CSV),
        metavar="PATH",
        help=(
            f"Path to qualifications CSV file.\n"
            f"Default: {_DEFAULT_CSV}"
        ),
    )
    parser.add_argument(
        "--hot-run",
        action="store_true",
        help=(
            "Perform actual upserts into MongoDB.\n"
            "Without this flag the script runs in DRY-RUN mode: it reads the CSV\n"
            "and logs what would happen, but writes nothing."
        ),
    )
    return parser.parse_args()


if __name__ == "__main__":
    try:
        asyncio.run(main(parse_args()))
    except KeyboardInterrupt:
        logger.info("Interrupted by user.")
    except Exception as exc:
        logger.error("Script failed: %s", exc, exc_info=True)
        sys.exit(1)
