name: Run Backend Tests

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ner, nel, classify, nel_v2, classify_v2]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.8.3

      - name: Install shared
        working-directory: backend/shared
        run: poetry install --no-root

      - name: Lock ${{ matrix.service }} dependencies
        working-directory: backend/${{ matrix.service }}
        run: poetry lock

      - name: Install ${{ matrix.service }} service
        working-directory: backend/${{ matrix.service }}
        run: poetry install

      - name: Run tests
        working-directory: backend/${{ matrix.service }}
        run: poetry run python -m pytest -v
